### ISSUE TITLE
プログラムについて

### ISSUE THREAD

**Issue by tkchgitstr10** [tkchgitstr10/hoge1#1]
・registerSchduleメソッドに数値を入力してKomaオブジェクトの数値を設定できなかった
scannerクラスが正しく動いているか怪しい
・と思ったけど
アルゴリズムの実証だけなので仮データをmainメソッド内で入力して動作の確認をします
インターフェイスから入力するときにもchatchやthrowが必要なのか気になる
教えてエロい人

**Comment by tkchgitstr10** [comment]
実行時エラー1(//registerSchedule(schedule);)
Exception in thread "main" java.lang.NullPointerException
        at test.buildKomaTime(test.java:91)
        at test.getNextKoma(test.java:106)
        at test.main(test.java:144)
